In [1]:
import pandas as pd
import networkx as nx
import numpy as np
from tqdm import tqdm

from april import Dataset
from april.processmining import ProcessMap
from april.fs import get_event_log_files
from april.fs import get_process_model_files

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
GPU found
Memory growth set

# Event Log information

A list of all event logs used in the evaluation

In [2]:
logs = sorted([e.name for e in get_event_log_files() if e.p == 0.3 and "bpic" not in e.model and "0.3-1" in e.name])
print(logs)

['gigantic-0.3-1', 'huge-0.3-1', 'large-0.3-1', 'medium-0.3-1', 'p2p-0.3-1', 'paper-0.3-1', 'small-0.3-1', 'wide-0.3-1']

In [3]:

columns = ['name', 'base_name', 'num_cases', 'num_events', 'num_activities', 
           'num_attributes', 'attribute_keys', 'attribute_dims', 
           'min_attribute_dim', 'max_attribute_dim',
           'min_case_len', 'max_case_len', 'mean_case_len']
df = []
for log in tqdm(logs):
    d = Dataset(log)
    dim_min = d.attribute_dims[1:].astype(int).min() if d.attribute_dims[1:].size else None
    dim_max = d.attribute_dims[1:].astype(int).max() if d.attribute_dims[1:].size else None
    df.append([log, log.split('-')[0], d.num_cases, d.num_events, d.attribute_dims[0].astype(int), 
               d.num_attributes - 1, d.attribute_keys[1:], d.attribute_dims[1:].astype(int), dim_min, dim_max,
               d.case_lens.min(), d.case_lens.max(), d.case_lens.mean().round(2)])
event_logs = pd.DataFrame(df, columns=columns)

100%|██████████| 8/8 [00:00<00:00, 121.86it/s]

gigantic-0.3-1 [155. 140.]
gigantic-0.3-1 [155. 140.]
gigantic-0.3-1 [155. 140.]
gigantic-0.3-1 [155. 140.]
gigantic-0.3-1 [155. 140.]
gigantic-0.3-1 [155. 140.]
huge-0.3-1 [109. 141.]
huge-0.3-1 [109. 141.]
huge-0.3-1 [109. 141.]
huge-0.3-1 [109. 141.]
huge-0.3-1 [109. 141.]
huge-0.3-1 [109. 141.]
large-0.3-1 [ 85. 141.]
large-0.3-1 [ 85. 141.]
large-0.3-1 [ 85. 141.]
large-0.3-1 [ 85. 141.]
large-0.3-1 [ 85. 141.]
large-0.3-1 [ 85. 141.]
medium-0.3-1 [ 65. 140.]
medium-0.3-1 [ 65. 140.]
medium-0.3-1 [ 65. 140.]
medium-0.3-1 [ 65. 140.]
medium-0.3-1 [ 65. 140.]
medium-0.3-1 [ 65. 140.]
p2p-0.3-1 [ 27. 141.]
p2p-0.3-1 [ 27. 141.]
p2p-0.3-1 [ 27. 141.]
p2p-0.3-1 [ 27. 141.]
p2p-0.3-1 [ 27. 141.]
p2p-0.3-1 [ 27. 141.]
paper-0.3-1 [ 29. 141.]
paper-0.3-1 [ 29. 141.]
paper-0.3-1 [ 29. 141.]
paper-0.3-1 [ 29. 141.]
paper-0.3-1 [ 29. 141.]
paper-0.3-1 [ 29. 141.]
small-0.3-1 [ 41. 141.]
small-0.3-1 [ 41. 141.]
small-0.3-1 [ 41. 141.]
small-0.3-1 [ 41. 141.]
small-0.3-1 [ 41. 141.]
small-0.3-1 [ 41. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]

## Basis for Table 1 in the Paper

In [4]:
event_logs

,name,base_name,num_cases,num_events,num_activities,num_attributes,attribute_keys,attribute_dims,min_attribute_dim,max_attribute_dim,min_case_len,max_case_len,mean_case_len
0,gigantic-0.3-1,gigantic,5000,39829,155,1,[user],[140],140,140,3,16,7.97
1,huge-0.3-1,huge,5000,53210,109,1,[user],[141],141,141,5,16,10.64
2,large-0.3-1,large,5000,67524,85,1,[user],[141],141,141,10,17,13.50
3,medium-0.3-1,medium,5000,41991,65,1,[user],[140],140,140,3,13,8.40
4,p2p-0.3-1,p2p,5000,53193,27,1,[user],[141],141,141,7,16,10.64
5,paper-0.3-1,paper,5000,60536,29,1,[user],[141],141,141,9,17,12.11
6,small-0.3-1,small,5000,53437,41,1,[user],[141],141,141,7,15,10.69
7,wide-0.3-1,wide,5000,41910,58,1,[user],[141],141,141,6,12,8.38

In [5]:
print(event_logs[['name', 'num_cases', 'num_events', 'max_case_len']])

             name  num_cases  num_events  max_case_len
0  gigantic-0.3-1       5000       39829            16
1      huge-0.3-1       5000       53210            16
2     large-0.3-1       5000       67524            17
3    medium-0.3-1       5000       41991            13
4       p2p-0.3-1       5000       53193            16
5     paper-0.3-1       5000       60536            17
6     small-0.3-1       5000       53437            15
7      wide-0.3-1       5000       41910            12

In [6]:
event_logs[['base_name', 'num_activities', 'num_cases', 'num_events', 'min_attribute_dim', 'max_attribute_dim']].groupby('base_name').agg(['count', 'min', 'max'])

          num_activities           num_cases             num_events         \
                   count  min  max     count   min   max      count    min
base_name
gigantic               1  155  155         1  5000  5000          1  39829
huge                   1  109  109         1  5000  5000          1  53210
large                  1   85   85         1  5000  5000          1  67524
medium                 1   65   65         1  5000  5000          1  41991
p2p                    1   27   27         1  5000  5000          1  53193
paper                  1   29   29         1  5000  5000          1  60536
small                  1   41   41         1  5000  5000          1  53437
wide                   1   58   58         1  5000  5000          1  41910

                 min_attribute_dim           max_attribute_dim
             max             count  min  max             count  min  max
base_name
gigantic   39829                 1  140  140                 1  140  140
huge       53210                 1  141  141                 1  141  141
large      67524                 1  141  141                 1  141  141
medium     41991                 1  140  140                 1  140  140
p2p        53193                 1  141  141                 1  141  141
paper      60536                 1  141  141                 1  141  141
small      53437                 1  141  141                 1  141  141
wide       41910                 1  141  141                 1  141  141

# Process Model Information

In [7]:
maps = sorted([m for m in get_process_model_files()])
df = []
for process_map in tqdm(maps):
    model = ProcessMap.from_plg(process_map)

    num_variants = len(model.variants.cases)
    max_case_len = model.variants.max_case_len

    nodes = model.graph.number_of_nodes()
    edges = model.graph.number_of_edges()
    dens = nx.density(model.graph)
    in_degree = np.mean([d[1] for d in model.graph.in_degree()])
    out_degree = np.mean([d[1] for d in model.graph.out_degree()])

    df.append([nodes, edges, num_variants, max_case_len, dens, in_degree, out_degree])
process_models = pd.DataFrame(df, index=maps, columns=['nodes', 'edges', 'num_variants', 'max_case_len', 'density', 'in_deg', 'out_deg'])

100%|██████████| 8/8 [00:00<00:00, 122.71it/s]

In [8]:
# process_models.loc[['paper', 'p2p', 'small', 'medium', 'large', 'huge', 'gigantic', 'wide', 'testing']].round(2)
process_models.loc[['paper', 'p2p', 'small', 'medium', 'large', 'huge', 'gigantic', 'wide']].round(2)

          nodes  edges  num_variants  max_case_len  density  in_deg  out_deg
paper        16     18             8            12     0.08    1.12     1.12
p2p          15     18             8            11     0.09    1.20     1.20
small        22     26             6            10     0.06    1.18     1.18
medium       34     48            25             8     0.04    1.41     1.41
large        44     56            28            12     0.03    1.27     1.27
huge         56     75            39            11     0.02    1.34     1.34
gigantic     80    119            71            11     0.02    1.49     1.49
wide         36     53            19             7     0.04    1.47     1.47